matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install pipenv
        - pipenv install
      script: pytest --tb=line

    - language: ruby
      rvm:
      - 2.3
      install:
        - bundle install
      script: "bundle exec jekyll build"


      before_script:
         - chmod +x ./script/cibuild.sh

      script: ./script/cibuild.sh

      branches:
        only:
          - master

      env:
        global:
          - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          - JEKYLL_ENV=production
      sudo: false

      deploy:
        provider: pages
        skip_cleanup: true
        keep-history: true
        local_dir: _site
        github_token: $GITHUB_API_KEY
        fqdn: avlanche.fr
        on:
          branch: master

notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update