# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Avlanche
email: admin@avlanche.fr
description: >- # this means to ignore newlines until "baseurl:"
  AVLANCHE est une plateforme de production artistique indépendante, qui va mettre en valeur des jeunes talents.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://avlanche.fr # the base hostname & protocol for your site, e.g. http://example.com

timezone: Europe/Paris

logo: /assets/images/logo.png

lang: fr_FR

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-bootstrap-sass
  - jekyll-contentblocks

color: "#ffef0d"

google_analytics: UA-128865273-1

mixpanel:
    production: 05912e902cc00998764d089eaf5fe545
    development: 895a012126965dd879c91d68fc43d163

get_form: 3506152a-666a-42fe-8240-bac9a28e9c65

cloudinary:
  cloud_name: avlanche-fr

instagram:
  username: _avlanche_

facebook:
  username: avlancheprod

youtube:
  username: UCQiHZVLeWioIjQJYVwIsLCA

collections:
  musique:
    output: true
  cinema:
    output: true
  photography:
    output: true
  mode:
    ouput: true
  artgraphique:
    output: true

defaults:
  - scope:
      path: ""
      type: "musique"
    values:
      layout: "thing"

  - scope:
      path: ""
      type: "cinema"
    values:
      layout: "thing"

  - scope:
      path: ""
      type: "photography"
    values:
      layout: "photo"


feed:
  collections:
    - photography
    - musique

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - script/
   - readme.md
   - CNAME
   - Gemfile*
   - Pipfile*
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - tests/
   - setup.cfg
